# Generated by Django 2.0.6 on 2018-06-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('etag', models.CharField(max_length=200)),
                ('last_modified', models.DateTimeField()),
            ],
        ),
    ]
